### ISSUE TITLE
 Criar regras de campos obrigatórios no InternalTransfer

### ISSUE THREAD

**Issue by marcelosv** [Sellers-Community/fitbank-mock#4]
**Contexto**
O Serviço que faz a transferencia interna, existem alguns campos obrigatórios.

**Objetivo da Issue**
Desenvolver as regras de campos obrigatótrios
Como sei quais os camps obrigatórios? Na documentação exitem a tag "opcional". Esse campos não são obrigatórios

**Link da documentação**
https://fitbank.com.br/developer/#api-P2P-InternalTransfer

**Serviço no projeto**
CreateInternalTransferSimpleService

**Observação**
Quem for desenvoler alguma feacture, mudar o status para "in progress"

**Comment by marcelosv** [comment]
@BSTK se vc terminou, marca a issue como finalizada

**Comment by BSTK** [comment]
@marcelosv eu não encontrei onde fechar. Precisa de acesso/permissão ?

**Comment by marcelosv** [comment]
O botao "Close Issue" nao aparece?

**Comment by BSTK** [comment]
@marcelosv Não aparece.
Testei aqui num repositório meu e deveria aparecer ai na seta (imagem anexo)

![nao-issue](https://user-images.githubusercontent.com/3992400/192171737-79660df8-c752-46f2-9887-4add1041a9d0.png)
